{
  "config_missing_fixtests": [],
  "config_missing_tests": [],
  "config_with_errors": [
    {
      "error": "Error while matching: Semgrep encountered an internal error: Expecting value: line 1 column 1 (char 0).\nsemgrep-core exit code: 0\nsemgrep-core command: /home/runner/work/semgrep/semgrep/cli/src/semgrep/bin/semgrep-core -json -rules /tmp/tmpr5pxgro8.json -j 2 -targets /tmp/tmp28e589ej -timeout 30 -timeout_threshold 0 -max_memory 0 -json_time -fast\nunexpected non-json output while invoking semgrep-core:\n--- semgrep-core stdout ---\ntargets/fixtest/test3.py:2\n exit(1)\ntargets/fixtest/test3.py:5\n exit(2)\n{\"matches\":[{\"rule_id\":\"test3\",\"location\":{\"path\":\"targets/fixtest/test3.py\",\"start\":{\"line\":2,\"col\":1,\"offset\":16},\"end\":{\"line\":2,\"col\":8,\"offset\":23}},\"extra\":{\"message\":\"Use \\\"sys.exit\\\" over the python shell \\\"exit\\\" built-in. \\\"exit\\\" is a helper\\nfor the interactive shell and is not be available on all Python implementations.\\nhttps://stackoverflow.com/a/6501134\\n\",\"metavars\":{\"$X\":{\"start\":{\"line\":2,\"col\":6,\"offset\":21},\"end\":{\"line\":2,\"col\":7,\"offset\":22},\"abstract_content\":\"1\"}},\"rendered_fix\":\"somethingElse(1)\",\"engine_kind\":\"OSS\"}},{\"rule_id\":\"test3\",\"location\":{\"path\":\"targets/fixtest/test3.py\",\"start\":{\"line\":5,\"col\":1,\"offset\":41},\"end\":{\"line\":5,\"col\":8,\"offset\":48}},\"extra\":{\"message\":\"Use \\\"sys.exit\\\" over the python shell \\\"exit\\\" built-in. \\\"exit\\\" is a helper\\nfor the interactive shell and is not be available on all Python implementations.\\nhttps://stackoverflow.com/a/6501134\\n\",\"metavars\":{\"$X\":{\"start\":{\"line\":5,\"col\":6,\"offset\":46},\"end\":{\"line\":5,\"col\":7,\"offset\":47},\"abstract_content\":\"2\"}},\"rendered_fix\":\"somethingElse(1)\",\"engine_kind\":\"OSS\"}}],\"errors\":[],\"skipped_rules\":[],\"explanations\":[],\"stats\":{\"okfiles\":1,\"errorfiles\":0},\"time\":{\"targets\":[{\"path\":\"targets/fixtest/test3.py\",\"rule_times\":[{\"rule_id\":\"test3\",\"parse_time\":0.006649971008300781,\"match_time\":0.005891084671020508}],\"run_time\":0.024755001068115234}],\"rules\":[\"test3\"],\"rules_parse_time\":0.0028409957885742188,\"max_memory_bytes\":36798464},\"rules_by_engine\":[[\"test3\",\"OSS\"]],\"engine_requested\":\"OSS\"}\n--- end semgrep-core stdout ---\n--- semgrep-core stderr ---\n<semgrep-core stderr not captured, should be printed above>\n--- end semgrep-core stderr ---\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep",
      "filename": "rules/fixtest/test3.yaml",
      "output": {}
    }
  ],
  "fixtest_results": {
    "targets/fixtest/test3.py": {
      "passed": false
    }
  },
  "results": {}
}